kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: access-all
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-access-all
subjects:
- kind: ServiceAccount
  name: default
  namespace: <kube-ns>
roleRef:
  kind: Role
  name: access-all
  apiGroup: rbac.authorization.k8s.io
