apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  ports:
  - port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    app: vault
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: vault
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  strategy: {}
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - image: vault
        name: vault
        command: ["/bin/vault", "server", "-config=/run/vault-config/vault.hcl"]
        ports:
        - containerPort: 8200
        resources: {}
        volumeMounts:
        - name: vault-config-volume
          mountPath: /run/vault-config
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
      volumes:
        - name: vault-config-volume
          configMap:
            name: vault
status: {}
---
apiVersion: etcd.coreos.com/v1beta1
kind: Cluster
metadata:
  name: vault-etcd
spec:
  size: 3
  version: 3.1.4
